repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.13
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      exclude: 'src/bitssh/__init__.py'
    # Run the formatter.
    - id: ruff-format
      exclude: 'src/bitssh/__init__.py'
