name: Feature request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: "feature"

body:
  - type: markdown
    attributes:
      value: Is your feature request related to a problem? Please describe.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what the problem is.
      placeholder : |
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder : |
        Ex. I want the solution like [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder : |
        Ex. I want to extend the function A by adding someting more
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder : |
        context, screenshots, related links , etc.
    validations:
      required: false
